### ISSUE TITLE
having this error when trying to run 

### ISSUE THREAD

**Issue by FJay81** [OpenSimTools/AMS2CM#113] opened 2024-04-09 17:12 UTC
this is the first time i have ever used this and i am constantly getting this error, ive tried reinstalling multimes to no avail

message:
**Version**: 0.3.0+Branch.tags-v0.3.0.Sha.7058b9431a7b4943ef4d66a6be5de08292948c42
**OS**: Microsoft Windows NT 10.0.22621.0
```
Sequence contains more than one matching element
   at AMS2CM.GUI.App.ThrowingModManager.FetchState() in D:\a\AMS2CM\AMS2CM\src\GUI\App.xaml.cs:line 72
   at AMS2CM.GUI.MainWindow.SyncModListView() in D:\a\AMS2CM\AMS2CM\src\GUI\MainWindow.xaml.cs:line 74
   at AMS2CM.GUI.MainWindow.Root_Loaded(Object sender, RoutedEventArgs e) in D:\a\AMS2CM\AMS2CM\src\GUI\MainWindow.xaml.cs:line 31
   at WinRT._EventSource_global__Microsoft_UI_Xaml_RoutedEventHandler.EventState.<GetEventInvoke>b__1_0(Object sender, RoutedEventArgs e)
   at ABI.Microsoft.UI.Xaml.RoutedEventHandler.Do_Abi_Invoke(IntPtr thisPtr, IntPtr sender, IntPtr e)
```

**Comment by paoloambrosio** [comment] 2024-04-09 20:49
This is covered in the FAQ on Discord...

> This happens at startup when CM finds more than one instance of the game on Steam.

...along with how to get rid of it by editing the `Config.yaml` file.

Going to close this issue because I was never able to reproduce the error on my setup. Please feel free to re-open it with more information if anyone can diagnose why that is happening. It is probably erroring [here](https://github.com/OpenSimTools/AMS2CM/blob/c22e0406133b51125a9fd9b134cf04d3def18973/src/Core/Games/Steam.cs#L28C73-L28C78) because it finds AMS2 in more than one Steam library folder.

**Closed by paoloambrosio** 2024-04-09 20:49 UTC
